# Generated by Django 2.0.5 on 2018-05-15 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extract_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='List_prepations',
        ),
        migrations.DeleteModel(
            name='Patiens',
        ),
        migrations.DeleteModel(
            name='Prepations',
        ),
    ]
