# Generated by Django 2.0.5 on 2018-06-13 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extract_app', '0003_recepts_id_prepations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recepts',
            name='id_patiens',
        ),
        migrations.RemoveField(
            model_name='recepts',
            name='id_prepations',
        ),
        migrations.AddField(
            model_name='recepts',
            name='patiens',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='recepts',
            name='prepations',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
