# Generated by Django 2.0.5 on 2018-06-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extract_app', '0004_auto_20180613_0633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recepts',
            old_name='patiens',
            new_name='lastname_patient',
        ),
        migrations.RenameField(
            model_name='recepts',
            old_name='prepations',
            new_name='name_patient',
        ),
        migrations.AddField(
            model_name='recepts',
            name='name_prepations',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='recepts',
            name='patronymic_patient',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
