# Generated by Django 2.0.5 on 2018-06-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extract_app', '0005_auto_20180613_0647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recepts',
            name='lastname_patient',
        ),
        migrations.RemoveField(
            model_name='recepts',
            name='name_patient',
        ),
        migrations.RemoveField(
            model_name='recepts',
            name='name_prepations',
        ),
        migrations.RemoveField(
            model_name='recepts',
            name='patronymic_patient',
        ),
        migrations.AddField(
            model_name='recepts',
            name='id_patiens',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='recepts',
            name='id_prepations',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='recepts',
            name='id_staff',
            field=models.IntegerField(default=1),
        ),
    ]
