# Generated by Django 2.0.5 on 2018-05-16 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='adress',
            new_name='address',
        ),
    ]
