# Generated by Django 2.0.5 on 2018-05-18 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration_app', '0002_auto_20180516_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='name',
        ),
        migrations.AddField(
            model_name='staff',
            name='login_employee',
            field=models.CharField(default=' ', max_length=150),
        ),
        migrations.AddField(
            model_name='staff',
            name='type_users',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AlterField(
            model_name='staff',
            name='address',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='passport',
            field=models.CharField(default=' ', max_length=11),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(default=' ', max_length=16),
        ),
        migrations.AlterField(
            model_name='staff',
            name='post',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='specialization',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
