# Generated by Django 2.0.5 on 2018-05-18 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration_app', '0003_auto_20180518_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='name_employee',
            field=models.CharField(default=' ', max_length=150),
        ),
    ]
