# Generated by Django 2.0.5 on 2018-05-18 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration_app', '0004_staff_name_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='login_employee',
        ),
    ]
