# Generated by Django 2.0.5 on 2018-05-18 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration_app', '0009_remove_staff_name_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='name_employee',
            field=models.CharField(default=' ', max_length=150),
        ),
    ]
