# Generated by Django 2.0.5 on 2018-05-18 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration_app', '0010_staff_name_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='name_employee',
            new_name='employee_name',
        ),
    ]
