# Generated by Django 2.0.5 on 2018-05-18 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration_app', '0011_auto_20180518_0452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='employee_name',
            new_name='name',
        ),
    ]
