# Generated by Django 2.0.5 on 2018-06-04 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry_app', '0002_auto_20180516_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepations',
            name='form_release',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AddField(
            model_name='prepations',
            name='maker',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
