# Generated by Django 2.0.5 on 2018-06-07 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry_app', '0004_auto_20180607_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patiens',
            name='phone',
            field=models.CharField(default=' ', max_length=15),
        ),
    ]
