# Generated by Django 2.0.5 on 2018-06-07 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry_app', '0005_auto_20180607_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='patiens',
            name='Recording_date',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AlterField(
            model_name='patiens',
            name='date_of_birth',
            field=models.CharField(default=' ', max_length=10),
        ),
    ]
