# Generated by Django 2.0.5 on 2018-06-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry_app', '0006_auto_20180607_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='patiens',
            name='lastname',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='patiens',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
