# Generated by Django 2.0.5 on 2018-06-07 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry_app', '0007_auto_20180607_0350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patiens',
            name='exmotion',
        ),
    ]
