# Generated by Django 2.0.5 on 2018-06-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry_app', '0008_remove_patiens_exmotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='patiens',
            name='patronymic',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
